### ISSUE TITLE
[Suggestion] Allow spark link to output in chat when run by console

### ISSUE THREAD

**Issue by Yamza** [lucko/spark#10]
Would be great to be able to run this and get the link when used with discord commands.

**Comment by lucko** [comment]
Should work already?

**Comment by Yamza** [comment]
It seems that it does indeed go into the ingame chat but does not come through in the discord. Not sure that's something you could change or if the chat mods would have to impliment. https://i.imgur.com/2fYYwQN.png

**Comment by lucko** [comment]
This should be fixed now in the latest versions. :)
