### ISSUE TITLE
[1.16.5] Attempting to create heap dump. "An error occurred whilst inspecting the heap." 

### ISSUE THREAD

**Issue by aking4125** [lucko/spark#100]
Hello,

When attempting to use the command `/spark heapsummary` I get a message in the chat.

`An error occurred whilst inspecting the heap.`

Looking at the Debug.log. I don't really see anything that is standing out. I'm trying to use this mod/command to investigate a memory leak problem with a modpack I'm trying to create. Attached is the Debug.log and latest.log (They've been zipped up due to the 10MB limit here)

Idk if there anything else I can provide. Any ideas? The `/spark profiler` command works but I want to see what is eating up all of my memory and was hoping this mod would help give me an idea.

Forge: 36.0.40
OptiFine HD U G7 pre11 is installed
Java: AdoptOpenJDK\jdk-8.0.282.8-openj9

[debug.zip](https://github.com/lucko/spark/files/6017206/debug.zip)
[latest.zip](https://github.com/lucko/spark/files/6017207/latest.zip)

**Comment by lucko** [comment]
spark heap summaries don't work with OpenJ9, you need to use a Hotspot JVM instead.

Creating a full heap dump should work though -- `/spark heapdump`, then analyse with a 3rd party tool like Eclipse Memory Analyser
