### ISSUE TITLE
Plugin spark v1.5.0 generated an exception while executing task 61416

### ISSUE THREAD

**Issue by cloakfox** [lucko/spark#104]
https://pastebin.com/FsUdJURM

**Comment by lucko** [comment]
Could you try using one of these builds and let me know if it fixes it :)

https://ci.lucko.me/job/spark/179/

**Comment by cloakfox** [comment]
Seems to be working now, thanks!

**Comment by lucko** [comment]
Cool! Pushed the fixed build to Spigot
