### ISSUE TITLE
[Feature] Upper tick threshold when profiling

### ISSUE THREAD

**Issue by KR33PY** [lucko/spark#105]
It'd be cool and provide more flexibility if something like `--only-ticks-under` was implemented (similar to `--only-ticks-over`)
For example, I'm interested in seeing the info only on 50-80ms ticks, but right now Spark doesn't provide such functionality.

**Comment by lucko** [comment]
I'm not sure why this would be useful - why would you want to limit a profile to *not* include laggy ticks?

**Comment by KR33PY** [comment]
There is a situation where I encounter two types of lag at the same time - 50-80ms and 100+ms.
If I profile using `only-ticks-over 50`, the resulting info gets blurred and it becomes harder to clearly distinct 50-80ms from 100+ms.

**Comment by lucko** [comment]
But both are causing lag right? There isn't really a good reason to need to separate them out in profiles.

**Comment by KR33PY** [comment]
If you don't find this request reasonable, then it's all good! I'll fork Spark and implement this myself for personal use when I have time.
Thanks for the feedback, anyway.

**Comment by lucko** [comment]
No worries, and sorry, I didn't mean to come across as argumentative!

Was just trying to make sure I had understood the reason for your request. I do think though that this functionality is a little too niche for inclusion in spark itself - hope you understand :)
