### ISSUE TITLE
Starting a profiler hangs the server

### ISSUE THREAD

**Issue by lucasvanhalst** [lucko/spark#107]
I recently updated spark from 1.4.3 to 1.5.2, and when running `spark profiler` now it says "Initializing a new profiler, please wait..." and then nothing happens anymore and the server forcefully shuts down after a minute.

[crash-2021-03-27_17.27.21-server.txt](https://github.com/lucko/spark/files/6216092/crash-2021-03-27_17.27.21-server.txt)

Looking at the log I'm not sure what the issue is, but it's probably the new async profiler that's stuck somewhere.
the crash log mentions line 45 here https://github.com/lucko/spark/blob/master/spark-common/src/main/java/me/lucko/spark/common/sampler/async/AsyncProfilerAccess.java#L45, but that is a simple System.getProperty, not sure why that would take more than 90 seconds...

**Comment by lucko** [comment]
Seems like your system is unable to use the native profiler, try using `/spark profiler --force-java-sampler` instead to start.
