### ISSUE TITLE
[Compatibility] Error - ViaVersion

### ISSUE THREAD

**Issue by Acenox** [lucko/spark#109]
Hello,

When a player tries to connect with the latest versions of ViaVersion (dev-build) a spark error appears in the console.

Error: https://pastebin.com/Un0Nhbcv
Spark: V1.5.2-bukkit (Latest)
ViaVersion : https://ci.viaversion.com/job/ViaVersion-DEV/
Spigot: GemSpigot - Fork of TacoSpigot-1.8.8

Best regards,

**Comment by Acenox** [comment]
@lucko any news regarding this error?

Best regards,

**Comment by Valyrox** [comment]
This is not a Spark issue but an Adventure Platform one (https://github.com/KyoriPowered/adventure-platform).

ViaVersion recently changed the implementation of the ViaManager, and they need to update accordingly for it to work properly.

**Comment by KennyTV** [comment]
Their latest snapshot build have it updated https://github.com/KyoriPowered/adventure-platform/commit/da5f89e9269a360e1d918c2da88c3ffbde7378fa

**Comment by lucko** [comment]
Should be fixed by ^
