### ISSUE TITLE
Async profiling not working

### ISSUE THREAD

**Issue by kristi71111** [lucko/spark#111]
Using /spark sampler = Profiler now active! (async)
Using  /spark sampler --timeout 300 =  Profiler now active! (built in java)

Not sure if this is intended or not but it seems that when you specificy a timeout value that the async engine is not used. Is there any way to force it or is this a bug/intended?

Running Sponge API 7

**Comment by DreiPixel** [comment]
i have that issue too. im using forge tho.
also the async results are empty.

**Comment by lucko** [comment]
The async profiler engine doesn't support timeouts - so, yep, it's intended :)
