### ISSUE TITLE
[bug (maybe)] system cpu usage with dedicated cpu cores

### ISSUE THREAD

**Issue by AggerTV** [lucko/spark#115]
Hello, I have a server with dedicated cpu cores, so my server actually doesn't have a system cpu usage, but the spark plugin still shows an incorrect (because the value shouldn't exist) value of the cpu usage of the system
![image](https://user-images.githubusercontent.com/55299038/119183552-8711de80-ba74-11eb-8fe6-cf9a3d84a5c3.png)

**Comment by lucko** [comment]
spark just reports what the JVM knows via the management interface.
