### ISSUE TITLE
Rcon Response is empty

### ISSUE THREAD

**Issue by DreiPixel** [lucko/spark#119]
im trying to send the "spark tps" command to my server via RCON but the response is empty. all other commands work fine. forge tps also works fine. any idea?

**Comment by lucko** [comment]
spark commands run async, so the response cannot be sent via RCON.

**Comment by consoleaf** [comment]
Even if they run async, could you maybe add a command to get the status of, for example, the last command? 
So we could:
- /spark tps
- /spark lastCommandStatus
- /spark lastCommandStatus
- repeat until you get an answer

**Comment by dirien** [comment]
Don't want to resurect this old issue, just add maybe a solution for all RCON user who stumbled over this. Like me.

You can use the [overrideTpsCommand](https://spark.lucko.me/docs/Configuration#overridetpscommand) functionality.

When done, as described you will get via tps the "normal" bukkit/papermc output:

```bash
> tps
[19:53:04 INFO]: TPS from last 5s, 1m, 5m, 15m: 20.0, 20.0, 20.0, 20.0
````
