### ISSUE TITLE
network problem

### ISSUE THREAD

**Issue by jiajiaxd** [lucko/spark#120]
I'm an owner of a chinese minecraft server.
I have got a problem when connecting to bytebin.lucko.me
Can you add a feature that supports network proxy?

**Comment by lucko** [comment]
Best bet is to proxy at a server level. I don't specifically block access from China.

**Comment by comendantmc** [comment]
It would also benefit users who are running servers in restrictive environments where there might not be an internet connection and only specific network interfaces are allowed. As this plugin heavily relies on the access to the internet this feature would be nice to have.
