### ISSUE TITLE
ars nouveau mod showing high server thread usage (went to the mod creator already)

### ISSUE THREAD

**Issue by Iacchus-sys** [lucko/spark#121]
profile:https://spark.lucko.me/RmrcsdcLgR
Ars-Nouveau issue:https://github.com/baileyholl/Ars-Nouveau/issues/295
baileyholl  i quote "There is nothing in this profiler that actually points to anything directly from this mod. 7% of that 11% are entirely vanilla bounding box calculations and movement, both of which use vanilla.

Are you actually having TPS issues? This profile is very strange and the numbers look massively inflated. 40% of the tick time is just in random chunk ticks, which would be concerning if this were a normal profile.

If you are actually experiencing issues, I would try to take another longer profile playing the game you normally do. If you still find large processing time for wildens, please post it.

If you are not experiencing any issues and /forge tps gives you 20 tps, profiling is pointless." i ask you please to look at this cause im at a loss on why the profiler shows the mod eating that much server thread.

**Comment by lucko** [comment]
Cause is clearly

```
com.hollingsworth.arsnouveau.common.entity.WildenStalker.tick() 11.07%
com.hollingsworth.arsnouveau.common.entity.WildenHunter.tick() 5.79%
com.hollingsworth.arsnouveau.common.entity.WildenGuardian.tick() 4.60%
```

those three mobs.

I don't see how this is an issue with spark - spark just reports the numbers 😛
