### ISSUE TITLE
Spark profiler will never initlialize

### ISSUE THREAD

**Issue by Seren541** [lucko/spark#122]
I've been getting an issue recently where I can't ever start my profiler. It doesn't matter if 2 players are online, or 10, I get the same issue nonetheless. I run the command and get:
`[20:17:20] [spark-fabric-async-worker/INFO]: [⚡] Initializing a new profiler, please wait...`
Also something to note, I recall getting previously getting this error on the lan server I was running, and it had the same error, but when I tried it just now it did work. This could be because it was on offline mode, but now that I have internet its on online mode, however I don't know if that affects it.
The server is obviously in online mode, and there are no indications why the profiler isn't starting. It doesn't work on the control panel or through in game commands.

**Comment by lucko** [comment]
Please try creating a thread/stack dump using the `jstack` command shorting after starting the profiler.

**Comment by Seren541** [comment]
I don't have access to the console, only the in game one.

**Comment by Seren541** [comment]
Also every other command works, only the spark profiler is broken.

**Comment by Seren541** [comment]
I got it to work using `--force-java-sampler`, although I have no clue why this works.

**Comment by lucko** [comment]
Ah, I guess the native one wasn't compatible with your system.. glad to hear that sorted it though.
