### ISSUE TITLE
Permission denied for Spark commands

### ISSUE THREAD

**Issue by LordHerdier** [lucko/spark#123]
**Version:** Spark 1.6.0 for Fabric 1.17 Server

**Issue:** Permission for all Spark commands are denied for OP players, but work in console.

**Fix:** DeOPing and OPing player again allows commands to be used.

**Notes:** Not sure on the reason for this, but it might be that I installed Spark _after_ initially OPing the player?

**Comment by capitalistspz** [comment]
in server.properties check what `op-permission-level` is set to
