### ISSUE TITLE
Gradle wrapper is out of date

### ISSUE THREAD

**Issue by embeddedt** [lucko/spark#129]
It looks like the Gradle wrapper is configured to download [Gradle 6.8](https://github.com/lucko/spark/blob/44c8ba9402dedbf7bc082c2384aeef680a5c0b7b/gradle/wrapper/gradle-wrapper.properties#L3). However, the Fabric subproject relies on [Loom 0.8](https://github.com/lucko/spark/blob/44c8ba9402dedbf7bc082c2384aeef680a5c0b7b/spark-fabric/build.gradle#L4), which depends on Gradle 7 & Java 16.

Normally this type of problem can easily be resolved by running `./gradlew wrapper --gradle-version <version>`, however, that doesn't work in this case as the `wrapper` task runs Loom first, which then fails because the version is out of date. It's a chicken-and-egg scenario.

The following workaround with manually replacing the distribution URL seems to resolve the issue for me:

```diff
diff --git a/gradle/wrapper/gradle-wrapper.properties b/gradle/wrapper/gradle-wrapper.properties
index 2a56324..0595cf7 100644
--- a/gradle/wrapper/gradle-wrapper.properties
+++ b/gradle/wrapper/gradle-wrapper.properties
@@ -1,5 +1,5 @@
 distributionBase=GRADLE_USER_HOME
 distributionPath=wrapper/dists
-distributionUrl=https\://services.gradle.org/distributions/gradle-6.8.2-bin.zip
+distributionUrl=https\://services.gradle.org/distributions-snapshots/gradle-7.2-20210702220150+0000-bin.zip
 zipStoreBase=GRADLE_USER_HOME
 zipStorePath=wrapper/dists
```

**Comment by lucko** [comment]
5e90d77503e0b5f9ef8cde2f44af65f32b071137

Thanks for the heads up :)
