### ISSUE TITLE
(Suggestion) Option to do an automatic heapdump before full GC

### ISSUE THREAD

**Issue by zNoah-1** [lucko/spark#140]
**Suggestion**
It would be nice to be able to automatically capture a heapdump before a full GC and have a command that would toggle the feature on (Since heaps can be very heavy).

**How I came up with it**
I'm having an issue where once in a while Java would attempt to move 2gb from Eden to Old gen, fill up and call a full gc, making the server pause for 10 seconds. So applying this suggestion would be pretty helpful for me.

Thanks.

**Comment by lucko** [comment]
Attaching a full memory profiler (like jProfiler or YourKit) is going to be the best way to disgnose an issue like this.
