### ISSUE TITLE
Weird results

### ISSUE THREAD

**Issue by andreasdc** [lucko/spark#141]
Latest profilers from bukkit shows really high percentage on threads, did anything change related with that?

**Comment by lucko** [comment]
Nope, should be similar?

Threads should always report 100% - you need to expand them further to find what's using the time.

**Comment by andreasdc** [comment]
> Nope, should be similar?
> 
> Threads should always report 100% - you need to expand them further to find what's using the time.

Sorry, I meant percentage on sleeping.

**Comment by andreasdc** [comment]
> Nope, should be similar?
> 
> Threads should always report 100% - you need to expand them further to find what's using the time.

What with that then?

**Comment by lucko** [comment]
Hi, so it might be different now the profiling engine is different.

However, I think the wallclock mode, added recently will resolve that and show a proportional amount of time spent sleeping.

Could you give that a try? https://spark.lucko.me/download

**Comment by andreasdc** [comment]
> Hi, so it might be different now the profiling engine is different.
> 
> However, I think the wallclock mode, added recently will resolve that and show a proportional amount of time spent sleeping.
> 
> Could you give that a try? https://spark.lucko.me/download

Yes sure I will give it a try tomorrow :)
