### ISSUE TITLE
Latest patch makes world not load up and stays stuck on world loading screen

### ISSUE THREAD

**Issue by WelpSTudent** [lucko/spark#150]
Using gd launcher's debugger, I was able to see that spark and opfitine were head butting I think, so I disabled spark and now the world will load properly. I can probably provide a latest.log to look at

**Comment by lucko** [comment]
Yes please!

**Comment by lucko** [comment]
I've tried to reproduce this using the latest Forge + spark + Optifine -- all working ok for me https://spark.lucko.me/5lifMbcG7b
