### ISSUE TITLE
[SPARK-SUGGESTION] A little helper in the view

### ISSUE THREAD

**Issue by Larskrs** [lucko/spark#153]
I really do love the recent changes and improvemets to the spark plugin. And i think that with this feature, spark could become the most used performance system ever.

The little helper would be very useful tool for the server admins.

Features: Shows users what server configurations would help speed up the server in specific lagg inducing problems. In the lagg viewer you could get like top 3 settings that would help you.

So if i was getting entity tick lagg alot, it could give it a score from how much percentage it effected the performance with all of the other lagg issues on the server. It could look like this.

Here are some settings you can use to improve performance:
1.    - spigot.yml | entity-tick-range.zombie = 4
2.    - spigot-yml | entity-tracking-range.player = 35
3.    - paper-yml | disable-hopper-tick = true

Not only just check for settings. You could also check for plugins like Chunky, LaggRemover/Clearlagg and Stackmob.

Here are some FREE plugins that might also help.
1.   - Stackmob <link>
2.   - Clearlagg <link>
3.   -Chunky <link>

Ofcourse if the server has the plugin it will remove the recommendation from the priority list.

If you think this could be a useful feature that you might want to add, Contact me and i can help configure some values that should affect the performace priority list.

**Comment by emielderckx** [comment]
I don't think this is a good idea. There are enough guides on the internet people could follow:

https://github.com/YouHaveTrouble/minecraft-optimization

https://eternity.community/index.php/paper-optimization/

PS: the plugins that you recommend make your performance worse (read about it in the guides above)

**Comment by kacperleague9** [comment]
clearlagg and stackmob big no no

**Comment by lucko** [comment]
I'm going to leave this for other guides. It's very difficult to create "automated advice" for this sort of thing - every server is different.
