### ISSUE TITLE
java.nio.BufferUnderflowException: null

### ISSUE THREAD

**Issue by LucidAPs** [lucko/spark#157]
I am using build 268 on a purpur 1.18.1 server. If I leave the profiler /spark profiler --thread * running for too long and then stop it, most of the times the upload will hang and never appear and If I try to run any profiler again it says. An active profiler is already running and if I try to stop it, it prints this and everything gets stuck.

https://nekobin.com/kagudireco

**Comment by LucidAPs** [comment]
Stuck again..... new message though.
https://nekobin.com/yicanavara

**Comment by lucko** [comment]
Hmm, seems like the temporary file that spark writes to may be being deleted.

Could you give some more details about your hosting environment? OS versions, etc

**Comment by LucidAPs** [comment]
> Hmm, seems like the temporary file that spark writes to may be being deleted.
> 
> Could you give some more details about your hosting environment? OS versions, etc

OVH dedicated machine, I am using Ubuntu 20.04.3 LTS (Focal Fossa), I've also installed a ptero panel for my servers. 
A bit unrelated perhaps but the command /spark profiler --thread * can also completely crash the server without any logs, warning or anything. Its like someone used a power kill switch.

**Comment by LucidAPs** [comment]
This is the error when a server crashes with /spark profiler --thread *
https://nekobin.com/yiyezemuli
@lucko

**Comment by lucko** [comment]
Most likely fixed in newer versions by an async-profiler update. Please feel free to re-open if it is still happening.

**Comment by lucko** [comment]
Oops, should be fixed in 49b8f5330ad8bf0b7203d507c356028014170b98

**Comment by LucidAPs** [comment]
> 

I am getting a different error now
https://nekobin.com/supakuweno

**Comment by hitanol** [comment]
Same issue here, after letting some time the profiler running without parameters added https://github.com/PurpurMC/Purpur/issues/1058

**Comment by lucko** [comment]
I've replied on your Purpur issue - basically, don't run the profiler for so long.
