### ISSUE TITLE
Redis support

### ISSUE THREAD

**Issue by deHasher** [lucko/spark#164]
How about adding the ability to set the server name in the configuration file and output placeholders to different servers using Redis. For example: server: lobby (in config) allows you to get a lobby server TPS from another server using %spark_tps_1m_lobby% or something similar. It would be very convenient to monitor several servers at once, and not connect to each one by finding out which server lags.

**Comment by lucko** [comment]
Out of scope for spark, and Redis is also the wrong tool for the job.

I suggest you check out https://github.com/Cubxity/UnifiedMetrics instead :)
