### ISSUE TITLE
RCON password visible in config view

### ISSUE THREAD

**Issue by YouHaveTrouble** [lucko/spark#169]
Configuration section in the report lists rcon password. It's possible that it could list other confidential data.

**Comment by lucko** [comment]
This has been fixed already in ce56c23132383bd5d865070f23dcb89e574b97cd

Please could you confirm it's ok in the latest build: https://spark.lucko.me/download

**Comment by YouHaveTrouble** [comment]
Yep. Downloaded just now, here's the report https://spark.lucko.me/KMd03l1aDp

**Comment by lucko** [comment]
Ok should be sorted now :)
