### ISSUE TITLE
Spark showing wrong number of CPU threads in informations section

### ISSUE THREAD

**Issue by magrigry** [lucko/spark#175]
I am running a server through pterodactyl. Pterodactyl is not configured to limit CPU. 

![image](https://user-images.githubusercontent.com/74878280/153276855-a7be96fb-8f92-490f-bf55-8da46db45761.png)

However, spark show that there is only one thread available. 
![image](https://user-images.githubusercontent.com/74878280/153276994-fdaf0e5e-cc79-4e4d-9b7f-79b766e0dcb4.png)

Even if I setup pterodatyl to use some specific core, spark still show that only one CPU thread is available. 
![image](https://user-images.githubusercontent.com/74878280/153277392-745e306e-c0fa-41b2-8196-0787c02cd214.png)

A similar server with a similar hardware, with the same configuraiton as above, but a different dedicate server, is showing the correct number of CPU threads. 
![image](https://user-images.githubusercontent.com/74878280/153277170-d26a8c6c-2a8a-46e8-8822-b22d9c9ae26a.png)

I am not sure if I am miss understanding something. I don't feel like that my server isn't only using 1 thread, I can see that CPU sometimes go over 100% based on pterodactyl graph (which mean that it use more than  a thread I guess) despite of what Spark says.

**Comment by lucko** [comment]
spark reports the result of this Java stdlib method call: https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Runtime.html#availableProcessors()

As far as I know, this is always a pretty accurate representation.

**Comment by magrigry** [comment]
Well I will try to post the issue on pterodactyl repo. 
Thanks
