### ISSUE TITLE
Seed in profile

### ISSUE THREAD

**Issue by rumickon** [lucko/spark#178]
Spark profiler send level-seed ftom server.properties and seed-\<feature\> from spigot.yml with default settings on Spigot/Paper.

**Comment by 44trent3** [comment]
You probably should be more specific to the issue, do you want Spark to omit the data?

**Comment by rumickon** [comment]
Yes, I think Spark should hide "level-seed" option when uploading the profile to web. How Paper timings do it.
This should work with the default settings.
