### ISSUE TITLE
Hide rcon password in server.properties configuration overview

### ISSUE THREAD

**Issue by bergerkiller** [lucko/spark#182]
Someone sent me a spark report and I noticed that there was a password in the server properties. This turned out to be the RCON password, which is used to connect to the RCON socket.

While this generally won't be a big security concern because probably nobody is exposing that socket to the outside world, in the off-chance it IS exposed somewhere, it would be better to not share that configuration option in reports.

![ScreenShot 2022-02-21 20 55 05](https://user-images.githubusercontent.com/957601/155018724-3461053c-3716-48f5-bdcb-50c4c867a789.jpg)

![image](https://user-images.githubusercontent.com/957601/155019541-64b78bfc-dc7b-4784-b939-11784effd617.png)

**Comment by lucko** [comment]
Encourage them to update, this has been fixed already :)

**Comment by bergerkiller** [comment]
Ah thanks, good to know. If I notice this again Ill tell them +1
