### ISSUE TITLE
[JVM] crash with spark

### ISSUE THREAD

**Issue by Lolothepro** [lucko/spark#184]
[hs_err_pid56036.log](https://github.com/lucko/spark/files/8177899/hs_err_pid56036.log)

**Comment by Lolothepro** [comment]
System information : 	Ryzen 1600
									GTX 1070
									Ubuntu
MultiMC
Java 17

**Comment by desht** [comment]
Also seeing this, my crash log looks pretty similar to above, and can be seen here: https://gist.github.com/desht/e7f523f68e5bb4d331fe7400126b5319

Also to note that preceding the crash, the log message `[WARN] Unknown DWARF instruction 0x2b in /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.470.103.01` was repeated many times.

Nvidia GTX 1660 on Linux Mint 19.03, Java 17.  From my Intellij development environment.

**Comment by lucko** [comment]
Should be fixed by 4fa21179b38a176c54b134295ae1c3a5e38f2288
