### ISSUE TITLE
Spark unable to upload profiles

### ISSUE THREAD

**Issue by Warhand** [lucko/spark#186]
My latest.log from the issue: https://pastebin.com/rNXaPP2A

The error as it appears ingame:
![image](https://user-images.githubusercontent.com/29134223/158155860-a2cf96a4-eec5-4026-a904-6030e8b77c9c.png)

This possibly has something to do with the fact that I had to contact my network admin to unblock the spark.lucko.me site before I could use it, but the site has been unblocked for a bit now, and I can access and use it fine by manually uploading profiles, so I'm unsure how it could be the cause of the issue.

I'm unsure what other information would be useful to have, aside from my modlist which I will also provide, but if theres anything else I can provide just let me know
Modlist: https://pastebin.com/GUbMfigp

**Comment by lucko** [comment]
Most likely a firewall / antivirus issue.

There may be some additional clues in the log files?
