### ISSUE TITLE
[Sponge API8+] (Re)Add statistical context 

### ISSUE THREAD

**Issue by Rasgnarok** [lucko/spark#188]
As discussed prior (https://github.com/lucko/spark/issues/5), Spark isn't quite complete as a statistical performance profiler. Indeed, it doesn't necessarily provide enough context on it's own to properly analyze the logging. Prior to Sponge API 8, Spark could be used in tandem with `/timings` for a complete trace of interpretational variables such as playercount, TPS, chunk, entity count, etc. 

While Spark's display has vastly improved (thanks Luck!) since I made that initial first suggestion, it still lacks a lot that could palliate the lack of timings in Sponge moving forward. I've made a ticket discussing this in https://github.com/SpongePowered/Sponge/issues/3649, but of course, this could also be solved by expanding the initial Spark use case.

**Comment by lucko** [comment]
The info available in spark is much better than it used to be!

What other metrics did you have in mind? Could you be specific?

**Comment by Rasgnarok** [comment]
Thanks for the prompt answer.

I'd mentioned this before, but seeing as Timings is being phased out by Sponge (API 8+), it would be interesting to see Spark address what currently would have required Timings to do. See https://spark.lucko.me/docs/misc/spark-vs-others#minecraft-timings, where you outline quite well why timings would have been preferred - accessibility, ease of display, as well as additional metrics.

**Comment by lucko** [comment]
Thanks - quite a few of the things there are out of scope for spark in my opinion.

spark is not intended to be a timings replacement, so striving for feature parity is not an aim of the project. However, I'm sitll open to specific suggestions that would fit in appropriately. :) feel free to open issues if you have any.
