### ISSUE TITLE
[1.18.2] Crash on world load

### ISSUE THREAD

**Issue by Jerome226** [lucko/spark#194]
[latest.log](https://github.com/lucko/spark/files/8456426/latest.log)
[crash-2022-04-09_03.00.30-client.txt](https://github.com/lucko/spark/files/8456427/crash-2022-04-09_03.00.30-client.txt)

Modlist: https://www.toptal.com/developers/hastebin/pubotilaye.apache

**Comment by lucko** [comment]
Please try downloading the latest version - this should be fixed now :)
