### ISSUE TITLE
Crash on Arch Linux, fabric

### ISSUE THREAD

**Issue by Redo11** [lucko/spark#198]
So, I just created a fresh fabric instance and installed newest Fabric API and Spark, launched it, went into singleplayer and typed /sparkc profiler. 
This crashed entire JDK VM
I use Zulu 17
https://paste.atlauncher.com/view/d0ed5185-6f2e-49b9-8cae-ffd3aa93caff

**Comment by Redo11** [comment]
OpenJDK 18 crashes too

**Comment by Redo11** [comment]
Problem insists on newest(1.9.1) version all the way back to 1.8.14 and probably further

**Comment by Redo11** [comment]
Java 18 temurin, Java 19 openjdk, java 17 jetbrains, Java 18 corretto, Java 17 graalvm all crash too, so I guess it's not version dependent after all...

**Comment by Redo11** [comment]
versions 1.6.2 and 1.8.6 work

**Comment by lucko** [comment]
Should be resolved -- https://spark.lucko.me/download
