### ISSUE TITLE
Show data for select period of time

### ISSUE THREAD

**Issue by Miclebrick** [lucko/spark#2]
Similar to how aikar timings lets you see data for a specific interval

**Comment by lucko** [comment]
See my reply on Discord.

> MicleBrick (حميد) - Yesterday at 23:08
How do you limit the spark thing to a specific timeframe, like you can with timings?

> Russian - Yesterday at 23:43
https://github.com/lucko/spark#commands
--timeout

> MicleBrick (حميد) - Today at 00:28
@Russian no, i mean if you have it running for 60 minutes, only show data for the time from 40 minutes after start to 50 minutes (as an example)

> Russian - Today at 01:16
oh like view data in a specific range... i do not think so
dont think it exists

> MicleBrick (حميد) - Today at 01:59
:frowning:
Luck ?

> Luck - Today at 09:37
you should only be running it for 1-3 minutes at a time


There's no need to refine the time period, the profiling data shown in the web is just a snapshot, there would be too much information to provide a complete breakdown.
