### ISSUE TITLE
Bitdefender blocking Spark

### ISSUE THREAD

**Issue by tonizombie** [lucko/spark#202]
My bitdefender is blocking any modpacks that have spark in them, 
the antivirus points to "me/lucko/spark/lib/adventure/text/format/StyleImpl.class"
It says the file was infected with Java.Trojan.GenericGBA.31530

Downloading latest file from curseforge gives same result (https://www.curseforge.com/minecraft/mc-mods/spark/files)
(Downloaded version: spark-1.9.1-forge.jar (MD5 ad7c5abdd6d83d0fd75dcdeb1e6b8ab3))

If this is an false positive (which i believe it is) could you please report the false positive?
https://www.bitdefender.com/consumer/support/answer/29358/

**Comment by lucko** [comment]
Yes it's a false positive.

I think it should be something you can report - I'm not a customer of Bitdefender and would prefer not to give them my name + email address. :) hope you understand.

**Comment by tonizombie** [comment]
Update: No longer triggers bitdefender
