### ISSUE TITLE
Spark Profiler Links Give 404 Error

### ISSUE THREAD

**Issue by lynical-dev** [lucko/spark#208]
I'm running a 1.15.2 forge server with some mods on it. All links that spark provides to view the results of the sampler for example return with a 404 error. 

This is one of my links, I've had others try the same one and different browsers etc. I am running spark on the client as well, could this be an issue? I've used it before and it worked fine, simply using /sparkc instead. I don't know if this is a version specific thing, or if all versions of spark have this issue right now.

![](https://i.gyazo.com/387e5f9df52e8dadfad2b74242b60bf0.png)

**Comment by lucko** [comment]
Hi, you can try replacing the sparkprofiler.github.io URL with spark.lucko.me.

That said, the viewer has changed quite a bit since 1.15.2 was released. Unfortunately I don't have the capacity to keep maintaining old versions forever. Sorry :(
