### ISSUE TITLE
1.19 Just does not work and crashes the server

### ISSUE THREAD

**Issue by Funtimes909** [lucko/spark#212]
Title, Log and mod list attached
[latest.log](https://github.com/lucko/spark/files/8873920/latest.log)
 
![image](https://user-images.githubusercontent.com/68979259/172944055-b03511bb-4e8b-4493-8111-7747ba6e1252.png)

**Comment by lucko** [comment]
Hm, it seems that spark *thinks* that `placeholder-api` is installed, but it actually isn't?

https://github.com/lucko/spark/blob/master/spark-fabric/src/main/java/me/lucko/spark/fabric/plugin/FabricServerSparkPlugin.java#L76

maybe try explictly installing it?

**Comment by Funtimes909** [comment]
How would i go about installing it?

**Comment by Funtimes909** [comment]
Nevermind I tried installing https://github.com/Patbox/TextPlaceholderAPI/releases/tag/2.0.0-beta.4%2B1.19 into the server folder and it still crashes

**Comment by Carterpersall** [comment]
I got the same issue. I fixed it by removing lines 42 and 76-78 from FabricServerSparkPlugin.java

**Comment by NakyoykaN** [comment]
Please fix.  I had to uninstall the 1.19 Fabric version of this mod because it was crashing on startup.

**Comment by Funtimes909** [comment]
> I got the same issue. I fixed it by removing lines 42 and 76-78 from FabricServerSparkPlugin.java

This did nothing for me
