### ISSUE TITLE
[Feature Request] Command to see last profiler

### ISSUE THREAD

**Issue by CayeOficial** [lucko/spark#220]
Would be nice a flag like `/spark profiler --show-last-profiler` that prints the last profiler link on the chat, of course with other info like the author and the formated time, so we don't have to go to the config for see it.

**Comment by fire7d** [comment]
Isnt `/spark activity` enough?

**Comment by CayeOficial** [comment]
yeah I figured out that after opening the issue lmao, you can ignore this
