### ISSUE TITLE
[Bug] feature-seeds not hidden (1.19 paper)

### ISSUE THREAD

**Issue by Pantera07** [lucko/spark#223]
world.yml
world_nether.yml
world_the_end.yml

feature-seeds not hidden (1.19 paper)

![1](https://user-images.githubusercontent.com/89838384/177063336-43d92f8f-0367-45e0-a61a-129c78226494.png)
![2](https://user-images.githubusercontent.com/89838384/177063339-d45a8928-4f23-46a4-9072-8410e2991fba.png)

**Comment by Pantera07** [comment]
https://github.com/lucko/spark/issues/189
https://github.com/lucko/spark/issues/178

**Comment by lucko** [comment]
814ac81af5c879a669b345a007a2ffbb1256aeb0
