### ISSUE TITLE
game crash at launch with version 1.9.25

### ISSUE THREAD

**Issue by Maxtar07** [lucko/spark#227]
I upgraded to the new version of spark (1.9.25) and when I launch my game, it crashes and doesn't launch while with the previous version it worked fine.

Attached is the crash report.
[crash-2022-07-15_12.43.56-client.txt](https://github.com/lucko/spark/files/9120177/crash-2022-07-15_12.43.56-client.txt)

**Comment by lucko** [comment]
Thanks 319aae27ad290338a5558ac53517e144254a86ce
