### ISSUE TITLE
heapdump and heapsummary can cause servers to lag and all players disconnect.

### ISSUE THREAD

**Issue by zhourui123** [lucko/spark#23]
sponge version: spongeforge-1.12.2-2838-7.1.7-RC3843.jar

heapdump and heapsummary command can cause servers to lag and all players disconnect.
About 30 players.
I'm afraid to analyze heap now

**Comment by md678685** [comment]
You need to freeze the JVM to take a heap dump. If you didn't, the contents of the heap would be constantly changing while you were trying to capture it and you wouldn't get a useful result.

**Comment by lucko** [comment]
Nothing spark can do to combat this unfortunately.
