### ISSUE TITLE
Almost all ticks exceed the threshold with --only-ticks-over

### ISSUE THREAD

**Issue by isuewo** [lucko/spark#234]
Here are two of the profiles I've created:

https://spark.lucko.me/231Ul0NfKr
https://spark.lucko.me/hFjXnM3l5G

The command I use is this: `/sparc profiler --only-ticks-over 50 --thread *` but I have tried without `--thread` and it still doesn't work properly

The Spark version is 1.9.29

I know for a fact that these values are wrong as the game runs at over 200fps and I also use MangoHud to confirm that the threshold is never actually exceeded

**Comment by lucko** [comment]
Check with `/spark tickmonitor`

To be honest, I am not sure how game ticks in the client correspond with FPS
