### ISSUE TITLE
Instant Crash After Enabling Profiler

### ISSUE THREAD

**Issue by Xarius86** [lucko/spark#251]
I'm running the latest versions of server software and plugins, and when I use `spark profiler --start` the server immediately crashes with no other indications for pertinent errors in` latest.log`. 

However, as another Discord user offered a suggestion for, when I run `spark profiler --force-java-sampler` a crash doesn't occur.

Pertinent information; Premium VPS offered through DigitalOcean. The server is running the latest, as of about an hour ago, Arch Linux distro, and current build of Purpur that includes spark. All of my additional plugins are current as of an hour ago as well. It's just really odd to see the entire server immediately collapse when it never has in the past. 

See Discord for posted logs.

**Comment by lucko** [comment]
Can you attach the logs here please?

**Comment by valeredev** [comment]
I have same error.
Running paper, ArchLinux up to date.
Tried with OpenJDK 19 and 17.

here so logs/dump. Running 

[latest.log](https://github.com/lucko/spark/files/10011425/latest.log)
[hs_err_pid34179.log](https://github.com/lucko/spark/files/10011427/hs_err_pid34179.log)

Thanks

**Comment by DylanDelobel** [comment]
Same issue, with [logs](https://log.mtxserv.com/ioNQZfM)

`spark profiler --force-java-sampler` worked for me

**Comment by UltraBlackLinux** [comment]
Can reproduce this issue on a fabric client. Above solution also worked for me

**Comment by embeddedt** [comment]
I've had the same issue on Arch for a while now; it's a SIGSEGV just like the above logs show.

**Comment by lucko** [comment]
Haven't seen this one reported for a while - closing
