### ISSUE TITLE
NotEnoughCrashes says its this mod that crashes my game

### ISSUE THREAD

**Issue by aMazeInRunar** [lucko/spark#252]
I have a report here: 
https://bytebin.lucko.me/3IyPd8OWYd
I'm clueless on what to do, might have something to do with the other mods

**Comment by aMazeInRunar** [comment]
Okay so, some more information, it doesn't work with Architectury.  which is needed for basically all Masa mods. I'm playing on 1.19 and it crashes as soon as I try to profile in singleplayer. It works on my server (pbb) because I dont have architectury in there.

**Comment by lucko** [comment]
Logs have expired (use https://pastes.dev in the future - the expiry is longer!)

but presumably this is fixed by https://github.com/lucko/spark/commit/2f81df7a1fa65e0cfe7301da27d9b47fa2f9a8f4
