### ISSUE TITLE
JVM Crash

### ISSUE THREAD

**Issue by falistos** [lucko/spark#256]
[hs_err_pid56036.log](https://github.com/lucko/spark/files/9847080/hs_err_pid56036.log)

Using async-profiler on OpenJDK 8 (build 1.8.0_342-8u342-b07-1-b07)
Spark version 1.9.39
PaperSpigot 1.8.8

It happens randomly a while after starting profiler.
After using a addr2line on the problematic frame, it appears that AsyncGetCallTrace is the cause, used by async-profiler lib

addr2line -e libjvm.so -C -f 0x64ce90
AsyncGetCallTrace

**Comment by lucko** [comment]
Should be fixed in the latest version, I've updated the version of async-profiler
