### ISSUE TITLE
Publish Forge 1.12.2 version

### ISSUE THREAD

**Issue by Yamza** [lucko/spark#26]
Using the current build errors expecting 1.13
https://hatebin.com/qohtivgyjw

**Comment by TheInfamousAlk** [comment]
I also have this issue. Most modpacks are 1.12 right now and I can't seem to find a download for 1.12 (and the download link doesn't actually specify what MC version it's made for)

**Comment by TheKineticz** [comment]
Also came here just to see if I could find previous versions.

**Comment by nonsintetic** [comment]
Same, is there a way we can get a legacy 1.12 version?

**Comment by Zalgo2462** [comment]
I'm looking for a 1.12 version as well.

**Comment by Yoosk** [comment]
I have archived one of latest available 1.12.2 versions, you can download it [here](https://dl.dropboxusercontent.com/s/3fuqise4uee9rt7/spark-forge.jar).

**Comment by MechanosG** [comment]
Same boat here.  Going to try Yoosk's link.  But having the last 1.12.2 version for download would be handy, since 1.12.2 modpacks are still the majority currently.

**Comment by JJJollyjim** [comment]
The last revision supporting 1.12 was `c8d631f`, if you'd rather build it yourself try a `./gradlew build` in that checkout.

**Comment by lucko** [comment]
I'll post an official build somewhere soon.

**Comment by noobanidus** [comment]
That would be amazing, thank you! I feel awkward linking people to a dropbox link.

**Comment by Yoosk** [comment]
You can use this link for even more awkwardness: [here](https://yoosk.pl/4JYbdAnA.jar).

**Comment by noobanidus** [comment]
I'm now imagining someone sneaking up behind me wearing a large coat, and throwing it open and saying, "Hey kid! You wanna download some JARs???"

**Comment by Ytoblo** [comment]
Waiting...

**Comment by CritFlaw** [comment]
So is @Yoosk 's link the only version available for 1.12.2 or is there something I'm missing?

**Comment by VitLogArx** [comment]
is there any progress? Searched 1.12.2 version of spark profiler, but there are no official source(

**Comment by RandomExplosion** [comment]
any progress?

**Comment by Jerome226** [comment]
when the 1.12 will become public...

**Comment by lucko** [comment]
Alright, sorry this has taken a while.

Unfortunately, the Forge tooling is **painfully slow** to use which made working on this... pretty horrible. I've actually tried multiple times over the past several months and given up each time after hitting a brick wall getting ForgeGradle to play nicely.

Anyway, it's done now. 1.12.2 is now a separate module, not just a branch, which means it should stay up-to-date with the rest of spark.

You can download from Jenkins as usual: https://ci.lucko.me/job/spark/

If someone could test and confirm here whether it works, that would be much appreciated. Once that has happened, I will upload it to CurseForge too.

**Comment by Yoosk** [comment]
Oh man, that means i can finally remove my mirrors? After you fix the crash that is: https://paste.ee/p/CyOd8

**Comment by lucko** [comment]
Please try again using the latest build :)

**Comment by Yoosk** [comment]
Seems to be working fine in single player and LAN https://spark.lucko.me/#c1XTnhHXAu

**Comment by lucko** [comment]
Cool, thanks, I've pushed it to CurseForge

**Comment by KweezyPlay** [comment]
where is 1.12.2 forge version? i don't see it

**Comment by Yoosk** [comment]
> where is 1.12.2 forge version? i don't see it

As the previous comment says, it is on curseforge
https://www.curseforge.com/minecraft/mc-mods/spark/files/all?filter-game-version=1738749986%3A628

**Comment by KweezyPlay** [comment]
thanks!
