### ISSUE TITLE
Error when entering any command

### ISSUE THREAD

**Issue by AVuTuVA** [lucko/spark#270]
If you go from 1.19.2 to server 1.12.2 and enter /spark tps, then there will be an error in the console, more details here:
https://github.com/ViaVersion/ViaVersion/issues/3155

**Comment by AVuTuVA** [comment]
?

**Comment by lucko** [comment]
https://github.com/lucko/spark/commit/d9655c40c02aef137c7a6a00a1cc90a1e6fb08d1
