### ISSUE TITLE
SIGSEGV after /sparkc profiler start

### ISSUE THREAD

**Issue by sudofox** [lucko/spark#271]
```
[19:32:23] [spark-worker-pool-1-thread-1/INFO]: [CHAT] [⚡] Starting a new profiler, please wait...
[WARN] Install JVM debug symbols to improve profile accuracy
[WARN] Install JVM debug symbols to improve profile accuracy
[WARN] Kernel symbols are unavailable due to restrictions. Try
  sysctl kernel.kptr_restrict=0
  sysctl kernel.perf_event_paranoid=1
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f67822f5aed, pid=1252404, tid=1254218
#
# JRE version: OpenJDK Runtime Environment (19.0.1+10) (build 19.0.1+10)
# Java VM: OpenJDK 64-Bit Server VM (19.0.1+10, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xe62aed]  JVM_handle_linux_signal+0x14d
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /run/media/aburk/Samsung USB/shared/instances/Fabric1.19.2/.minecraft/core.1252404)
#
# An error report file with more information is saved as:
# /run/media/aburk/Samsung USB/shared/instances/Fabric1.19.2/.minecraft/hs_err_pid1252404.log
[thread 1252633 also had an error]
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Process was killed by user.
```

Just downloaded the latest spark fabric jar today to try to find the source of a bunch of frame loss. No java stacktrace to speak of

I can't recall if coredumps have any privileged info in them. Not that it matters, but there was no coredump generated, I looked to see if it was there and it wasn't. I did attach hs_err_pid1252404.log though (this happened twice, no coredump on either of them, and the first time, i let it sit for much longer after freezing as MC still had my mouse captured.)

Manjaro, everything is up to date afaik

**Comment by CutestNekoAqua** [comment]
okay, same on manjaro, works on jdk 17 but not on jdk 19

**Comment by sudofox** [comment]
> okay, same on manjaro, works on jdk 17 but not on jdk 19

How are you able to get JDK 17 on Manjaro? Did you sideload it or something?

I remember great pains on Arch trying to downgrade my Java version or sideload another version for unrelated compatibility issues.

**Comment by CutestNekoAqua** [comment]
> > > okay, same on manjaro, works on jdk 17 but not on jdk 19
> > 
> > 
> > How are you able to get JDK 17 on Manjaro? Did you sideload it or something? I need spark for figuring out what's causing my intermittent tick lag.
> > I remember great pains on Arch trying to downgrade my Java version or sideload another version for unrelated compatibility issues.
> 
> using the repos. and I started my server from intellij which allows for choosing the jdk to run files with

its called openjdk-17 or smth like that

**Comment by sudofox** [comment]
Ahh I see. I might just download Java 17 source and build it to try it out or something.

**Comment by lucko** [comment]
I've implemented a temporary solution: 

<img width="986" alt="Screenshot 2022-11-27 at 23 37 31" src="https://user-images.githubusercontent.com/8352868/204165867-64414f53-efe1-47cd-b91e-cc3bf6bad076.png">

Unfortunately the problem is with async-profiler (the library the spark uses to gather profiling data) so there's not much I can do to resolve it. I have just updated spark to use the latest version though - so hopefully that will help!
