### ISSUE TITLE
Server Crashing because Profiler

### ISSUE THREAD

**Issue by DoTrONoL** [lucko/spark#273]
```console
container@pterodactyl~ Server marked as running...
>....JVMDUMP012E Error in System dump: The core file created by child process with pid = 186 was not found. Expected to find core file with name "/home/container/core"
JVMDUMP032I JVM requested Java dump using '/home/container/javacore.20221123.103140.1.0002.txt' in response to an event
JVMDUMP010I Java dump written to /home/container/javacore.20221123.103140.1.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/container/Snap.20221123.103140.1.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /home/container/Snap.20221123.103140.1.0003.trc
JVMDUMP032I JVM requested JIT dump using '/home/container/jitdump.20221123.103140.1.0004.dmp' in response to an event
JVMDUMP051I JIT dump occurred in 'Async-profiler Sampler' thread 0x000000000372CE00
JVMDUMP010I JIT dump written to /home/container/jitdump.20221123.103140.1.0004.dmp
JVMDUMP013I Processed dump event "abort", detail "".
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
```

The server is crashing because of auto-start added in ver:
> [v1.9.49](https://github.com/lucko/spark/commit/f2d77d875f32f107987c93da1f90529fc6812444) - Background profiler | 2022-11-13
Atm I'm using ver _v1.9.47_, since I can't download the _.48_

I'm wondering if you could add an option to disable auto-start background profiler. Since that version, I'm not updating because it crash before I use the command `/spark profiler cancel`, that I can only use when server says "Marked as started".

I know it's something I should edit on my server, but would be very good since you add something like this. `/spark profiler disable-autostart`

**Comment by lucko** [comment]
I've implemented a temporary solution: 

<img width="986" alt="Screenshot 2022-11-27 at 23 37 31" src="https://user-images.githubusercontent.com/8352868/204165867-64414f53-efe1-47cd-b91e-cc3bf6bad076.png">

Unfortunately the problem is with async-profiler (the library the spark uses to gather profiling data) so there's not much I can do to resolve it. I have just updated spark to use the latest version though - so hopefully that will help!
