### ISSUE TITLE
Server gets stuck starting with [spark] Timed out waiting for world statistics.

### ISSUE THREAD

**Issue by TheDeafCreeper** [lucko/spark#277]
Server Version: Purpur 1.19.2-1857 (Latest as of writing)
Spark Version: v1.10.12

Server Log: https://pastebin.com/vQYk8KPp

The issue just randomly started when the server did it's scheduled restart last night and had been stuck like that for 7 hours before I saw it was stuck.

**Comment by TheDeafCreeper** [comment]
Update: This may not be a spark issue, after switching to paper to try removing spark the server's hanging at the same point (just without the spark warnings)

**Comment by lucko** [comment]
The spark messages are just because the server didn't start within 1 minute of spark enabling.

```
[15:56:04] [Server thread/INFO]: [CommandSync] Enabling CommandSync v2.8.2*
[15:56:04] [Server thread/INFO]: Configuration file loaded.
```

If I had to guess, it's that plugin ^
