### ISSUE TITLE
heapsummary ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by JohnnyPixelz** [lucko/spark#29]
Just after downloading and installing the plugin, /spark heapsummary throws this error. I was able to heapdump just fine though.

> [21:21:18 INFO]: [⚡] Creating a new heap dump summary, please wait...
> [21:21:18 INFO]: [⚡] An error occurred whilst inspecting the heap.
> [21:21:18 WARN]: java.lang.ArrayIndexOutOfBoundsException: 30
> [21:21:18 WARN]: at me.lucko.spark.common.util.TypeDescriptors.getJavaType(TypeDescriptors.java:72)
> [21:21:18 WARN]: at me.lucko.spark.common.util.TypeDescriptors.getJavaType(TypeDescriptors.java:65)
> [21:21:18 WARN]: at me.lucko.spark.common.util.TypeDescriptors.getJavaType(TypeDescriptors.java:35)
> [21:21:18 WARN]: at me.lucko.spark.common.heapdump.HeapDumpSummary.lambda$createNew$0(HeapDumpSummary.java:97)
> [21:21:18 WARN]: at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> [21:21:18 WARN]: at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
> [21:21:18 WARN]: at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
> [21:21:18 WARN]: at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
> [21:21:18 WARN]: at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
> [21:21:18 WARN]: at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> [21:21:18 WARN]: at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
> [21:21:18 WARN]: at me.lucko.spark.common.heapdump.HeapDumpSummary.createNew(HeapDumpSummary.java:101)
> [21:21:18 WARN]: at me.lucko.spark.common.command.modules.MemoryModule.lambda$null$0(MemoryModule.java:61)
> [21:21:18 WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
> [21:21:18 WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
> [21:21:18 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [21:21:18 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [21:21:18 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by lucko** [comment]
Should be fixed in the latest versions.
