### ISSUE TITLE
Suggestion #enhancement- Event sparks section or something similar

### ISSUE THREAD

**Issue by Yomamaeatstoes** [lucko/spark#295]
When I look at timing' reports, I can see events. But that is not the case with spark, I think It would be cool if this was the case, and whether that could be integrated with its own section or something. Like being integrated into the spark reports, so people can have further detail. I have found some events have caused lag which is reported in timings, but not spark profiler, which I feel like if it had this feature would give people a lot more insight.

Spark tracks general method calls and not events specifically, why can't it do both. I was looking in the discord and some people were talking about this as well. It would be a nice feature

plugins/spark/heap-2023-01-27_16.29.06.hprof

**Comment by lucko** [comment]
Unfortunately this isn't possible in spark due to the way spark samples for its data
