### ISSUE TITLE
[Feature Request] Get information of active spark in real time 

### ISSUE THREAD

**Issue by NewZAZ** [lucko/spark#299]
What I ask is to have the information: 
% of usage of each plugin
The name of the plugin
and all other information via the api and all this in real time.

I propose this because I saw that now we can open the spark without it stopping.

**Comment by RedstoneFuture** [comment]
`% of usage of each plugin` Do you mean the RAM?

**Comment by NewZAZ** [comment]
> `% of usage of each plugin` Do you mean the RAM?

Yes and other.

**Comment by lucko** [comment]
The percentage (cpu wise) is shown in the viewer, it's not easily possible to show memory usage per-plugin
