### ISSUE TITLE
Feature Request - Have an option to go deeper into the metric

### ISSUE THREAD

**Issue by Yomamaeatstoes** [lucko/spark#307]
For example, be able to look at plugins metrics for things like looking at CPU, RAM, Tick usage and other things. As for right now, the plugins section mostly only looks at one thing which I feel like could be more detailed. Spark is used a lot so it would be able to see more data for these things.

**Comment by Yomamaeatstoes** [comment]
@sk89q @Draradech @pschichtel @mdcfe

**Comment by pschichtel** [comment]
@Yomamaeatstoes not sure what you are trying to accomplish here by tagging a bunch of people. I'm assuming pull requests are welcome, start writing code.

**Comment by Yomamaeatstoes** [comment]
lmaooo fair

**Comment by Yomamaeatstoes** [comment]
I just saw those, and I thought why not.

**Comment by Yomamaeatstoes** [comment]
I will put a team together and do a pull request ( :
