### ISSUE TITLE
My server crash 

### ISSUE THREAD

**Issue by Ludodo2002** [lucko/spark#308]
Hello when I install spark on my server after 2 minutes my server stops for no reason with the following error and it also generates a file https://drive.google.com/file/d/1UxiHHMu4MaZcwsc81r9tA81ysldx15U2/view?usp=sharing

JVMDUMP039I Processing dump event "abort", detail "" at 2023/03/24 09:23:21 - please wait.
JVMDUMP032I JVM requested System dump using '/home/container/core.20230324.092321.1.0001.dmp' in response to an event
JVMDUMP010I System dump written to /home/container/core.20230324.092321.1.0001.dmp
JVMDUMP032I JVM requested Java dump using '/home/container/javacore.20230324.092321.1.0002.txt' in response to an event
JVMDUMP010I Java dump written to /home/container/javacore.20230324.092321.1.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/container/Snap.20230324.092321.1.0003.trc' in response to an event
[09:23:24 INFO]: -52536
JVMDUMP010I Snap dump written to /home/container/Snap.20230324.092321.1.0003.trc
JVMDUMP032I JVM requested JIT dump using '/home/container/jitdump.20230324.092321.1.0004.dmp' in response to an event
JVMDUMP051I JIT dump occurred in 'Async-profiler Sampler' thread 0x0000000003AF3400
JVMDUMP010I JIT dump written to /home/container/jitdump.20230324.092321.1.0004.dmp
JVMDUMP013I Processed dump event "abort", detail "".

**Comment by bridgelol** [comment]
Same issue on my end

**Comment by lucko** [comment]
Please re-open a new issue if this is still a problem
