### ISSUE TITLE
Background profiler

### ISSUE THREAD

**Issue by andreasdc** [lucko/spark#316]
I think background profiler should be disabled by default.

**Comment by lucko** [comment]
I don't :)

you can disable it in the configuration file on your servers though

**Comment by iTrooz** [comment]
Would it be possible to add some documentation about the performance impact of the background profiler ? e.g. in https://spark.lucko.me/docs/Configuration

**Comment by andreasdc** [comment]
> I don't :)
> 
> you can disable it in the configuration file on your servers though

I don't think that's efficient
