### ISSUE TITLE
Crashes in restricted environment

### ISSUE THREAD

**Issue by 0xpr03** [lucko/spark#318]
Just leaving a note here that if you see a singal 31 JVM crash with
```
[WARN] Install JVM debug symbols to improve profile accuracy
[WARN] open("/proc/kallsyms"): Permission denied
```

Then some modpack is using spark, the JVM profiler tries to load some stuff for profiling which is restricted in your environment (sandboxing via systemd) and thus this crashes the whole JVM.
Setting `backgroundProfiler: false` in `config/spark/config.json` solves that issue.

**Comment by seyfahni** [comment]
For anyone else suffering this issue: Disabling `ProtectKernelTunables` fixes this specific issue.
```
[Service]
ProtectKernelTunables=no
```

Though, I have other restrictions in place and my server still crashes with spark installed.
