### ISSUE TITLE
[SpongeForge 1.12.2] Spark not initalizing 

### ISSUE THREAD

**Issue by Discount-Milk** [lucko/spark#319]
Windows 10
Java Adoptium 1.8.0_332 
Forge 1.12.2 build 2860

Error logs: https://mclo.gs/uvnVZHD

Mods installed: 
spongeforge-1.12.2-2838-7.4.8-RC4142 
spark-1.10.37-sponge7

**Comment by mnixry** [comment]
same issue here

**Comment by lucko** [comment]
Should be fixed in the latest version
