### ISSUE TITLE
spark won't launch on paper 1.8.8

### ISSUE THREAD

**Issue by haeiven** [lucko/spark#32]
Hello,

I'm having this error when enabling spark on my server: https://paste.soleria.eu/risimidugo.cs

My server is running paper 1.8.8.

Best regards,

**Comment by lucko** [comment]
I'm guessing another plugin is shading an outdated version of the text library.

**Comment by haeiven** [comment]
Is there a way to fix it?

**Comment by lucko** [comment]
Fixed by 66c983aa47be8395cd6d163f43842fd2042f4f3d
