### ISSUE TITLE
Spark claims profiler has started (when it has not) fabric 1.19.4

### ISSUE THREAD

**Issue by KidOfCubes** [lucko/spark#322]
Logs: https://mclo.gs/9ZgV7xX
Running `/sparkc profiler start` immediately after going into a singleplayer world claims that the profiler has already started in the logs, `/sparkc profiler info` and `/sparkc profiler stop` both claim that there isn't a profiler running.

**Comment by lucko** [comment]
When running spark on an integrated server, you'll need to stop the server background profiler `/spark profiler stop` before starting the client `/sparkc profiler start`
