### ISSUE TITLE
Suggestion: Auto-timeout setting in config.

### ISSUE THREAD

**Issue by Hanoverfist** [lucko/spark#325]
Someone had left Spark profiler running on our server. It kept running and running and restarting itself and lagging the server. Obviously, this is our staff's fault. As a sever admin it would be nice if I could configure an automatic shutoff time limit for spark profiles in the config. i.e. After 60 seconds it shuts off no matter what - unless admin maybe?

This is just a QOL issue.

**Comment by lucko** [comment]
Newer versions of spark will cap the data to 1h (but the profiler will keep running)

I think this is probably ok
