### ISSUE TITLE
Errors when a profile is uploading 

### ISSUE THREAD

**Issue by dmodoomsirius** [lucko/spark#331]
Minecraft 1.19.2
forge version: 43.2.7
spark version: 1.10.3 (latest released version on Curseforge)

After i ran a 5 min profile when it stopped and uploaded the profile results to the web viewer the link below was spammed in the console along with the log file. I am reporting this incase you were not made aware of these ClassNotFoundException's. It does not crash the server just spams the console. 

https://gist.github.com/dmodoomsirius/ee73db432996fd8141b0b95e4f680c41

**Comment by lucko** [comment]
I think this is probably a forge classloading bug
