### ISSUE TITLE
Timed out waiting for world statistics

### ISSUE THREAD

**Issue by BlackAures1** [lucko/spark#335]
spark-1.10.37-forge.jar

When I try to save the results of the check, the world freezes and I have to crash it through the task manager. The logs show this error. I have used Spark before and had no problems. What can it be related to?

[latest.log](https://github.com/lucko/spark/files/11711584/latest.log)
[debug.log](https://github.com/lucko/spark/files/11711585/debug.log)

![image](https://github.com/lucko/spark/assets/43911230/c5254daa-d836-4ede-a6d9-b4247b3dd163)

**Comment by lucko** [comment]
Please re-open a new issue if this is still a problem
