### ISSUE TITLE
Fatal error after loading into world

### ISSUE THREAD

**Issue by jschenke488** [lucko/spark#339]
After loading into any world, a fatal error is thrown instantly causing a crash. There is no crash report because it was not a regular Minecraft crash. https://mclo.gs/R9h6GqT

**Comment by izfar** [comment]
I had a similar issue. Fixed mine by downgrading to java 17.0.6. Apparently it might be a java 17.0.7 Mac arm64 exclusive bug: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3325#issuecomment-1544401161

**Comment by lucko** [comment]
Doesn't look spark related
