### ISSUE TITLE
Issues between spark Agricraft and connected textures mods. 

### ISSUE THREAD

**Issue by FullMetalMaster** [lucko/spark#349]
mods involved
spark
AgriCraft
Fusion (Connected Textures)
ConnectedTexturesMod
With spark installed crops from agricraft are invisible, with these 2 connected texture library's 
![image (1)](https://github.com/lucko/spark/assets/52523300/19881ec5-276c-44bd-8465-45dad4c00b07)
![image](https://github.com/lucko/spark/assets/52523300/101f8e42-1b7d-4ba6-9a4c-def241f88a12)
lastest logs
[latest.log](https://github.com/lucko/spark/files/12139915/latest.log)

**Comment by FullMetalMaster** [comment]
1.18.2 lastest forge btw

**Comment by lucko** [comment]
Sorry I'm only supporting the latest MC versions on Forge/Fabric
