### ISSUE TITLE
spark-forge tab completion problems

### ISSUE THREAD

**Issue by Darkere** [lucko/spark#35]
When using tab complete on any --options it will delete the previous inputs.

For example typing /spark sampler --time then tab-complete reverts to /spark --timeout.

spark-forge

**Comment by prplz** [comment]
This is still a problem for me on spark-fabric

**Comment by lucko** [comment]
Client or server side? (i.e. are you using `/spark` or `/sparkc`?)

**Comment by prplz** [comment]
Server side. `/spark profiler --time<tab>` results in `/spark --timeout` in the chat box.

**Comment by lucko** [comment]
Should be fixed by the above commit - thanks :)
