### ISSUE TITLE
Question about spark on waterdall

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [lucko/spark#36]
Im looking for what is causing lag on waterfall and im using
`/sparkb sampler --thread * --combine-all`

but im not sure if thats the proper way to find it. After some time my waterfall is using 70% of cpu and starts lagging a lot. What should be proper flags to find what is causing that?

Spark with flags i've used doesnt say much:
https://sparkprofiler.github.io/#af1UqnDE1j

**Comment by Kryniowesegryderiusz** [comment]
@lucko could you look if the command im using to profile waterfall is proper?

**Comment by lucko** [comment]
Yep that command looks correct.
