### ISSUE TITLE
Crash when loading arguments for /sparkclient command in Quilt

### ISSUE THREAD

**Issue by sleepy-evelyn** [lucko/spark#370]
### Description

Crashes on quilt when typing sparkclient command

### Reproduction Steps

Type /sparkclient and then press space and the game crashes.

### Expected Behaviour

It not to crash

### Platform Information

* Minecraft Version:  1.20.1
* Platform Type:  client
* Platform Brand:  Quilt
* Platform Version: Quilt 0.21.0-beta.4

### Spark Version

1.10.53-fabric

### Logs and Configs

https://mclo.gs/WKnVYw3

**Comment by Silveere** [comment]
Does this issue go away if you disable Figura? If so, it's probably not an issue with Spark, but is more likely https://github.com/FiguraMC/Figura/issues/121.

**Comment by sleepy-evelyn** [comment]
Yeah I think it's an issue with Figura. I removed it recently due to other reasons and it works now
