### ISSUE TITLE
Spark crashes my server after it starts. 

### ISSUE THREAD

**Issue by Goinging** [lucko/spark#377]
### Description

My server crashes whenever spark is installed on it. I am using the bukkit version and I tried the most recent development build as well as the one on the spigot page. It spits out a weird error and creates a few files along with it.

### Reproduction Steps

1. Download spark and restart the server.
2. Server boots and crashes immediately after, sometimes with a 5-10 minute delay. 

### Expected Behaviour

The plugin doesn't crash the server

### Platform Information

* Minecraft Version: 1.20.2
* Platform Type: server
* Platform Brand: Paper
* Platform Version: git-Paper-318

### Spark Version

V1.10.34

### Logs and Configs

https://pastebin.com/5xc0w2VE
https://pastebin.com/6rzUe815

### Extra Details

If I had to guess, this is probably a compatibility issue with something. If it would help I can provide a plugin list.

**Comment by Sobble2546** [comment]
Im having the same issue

**Comment by Goinging** [comment]
Turns out this had something to do with the server host we where on cause I have tested the same server on different hosts and it works fine. The server host we did use was Berrybyte if anyone is curious. I am going to close this for now.
