### ISSUE TITLE
heapsummary crashed the server

### ISSUE THREAD

**Issue by Ahmadh26** [lucko/spark#39]
downloaded spark, put the plugin in the server and rebooted. after a while i went to do /spark heapsummary but my server crashed.

i have 4 players on at the time (if it matter)
here is the console log from the crash:
[2020-03-17-3.log](https://github.com/lucko/spark/files/4342494/2020-03-17-3.log)

server running mc version 1.15.2
6GB memory 3vCores 40Gb Disk space.

thanks.

**Comment by lucko** [comment]
Fixed by 93f8b0fa68417c4a876be79aac8aee359ad1a25d
