### ISSUE TITLE
Don't include spark/warmroast threads in the profiler output.

### ISSUE THREAD

**Issue by Cybermaxke** [lucko/spark#4]
When running `/profiler start --thread *` all threads are included, even the profiler threads. This causes a huge list of spark worker threads in the output which I don't need.
![capture](https://user-images.githubusercontent.com/1364375/40934265-8be92778-6834-11e8-9eb9-89749b55f0df.PNG)
Looking at the scroll bar you can see how long the list is beyond the image, at the bottom there are only 3 threads that are actually useful.

**Comment by lucko** [comment]
This should be resolved already in the newer versions (8b5071cdc5bd2609ee4f3805e3a54ced7f3d4df8)

(I don't think they're on Ore yet tho)

You could try the jar from here https://ci.lucko.me/job/spark/

**Comment by lucko** [comment]
It should also generate far less threads, that was a bug :p

**Comment by Cybermaxke** [comment]
Yeah, was using the latest version from Ore. The jar from the CI worked. Thanks :)

**Comment by lucko** [comment]
Ok awesome :)
