### ISSUE TITLE
[STDERR] [sun.instrument.InstrumentationImpl] WARNING\: A Java agent has been loaded dynamically 

### ISSUE THREAD

**Issue by ghost** [lucko/spark#404]
### Description

In java 21, spark says this:

[STDERR] [sun.instrument.InstrumentationImpl] WARNING\: A Java agent has been loaded dynamically (/tmp/byteBuddyAgent8430892618251552283.jar)
WARNING\: If a serviceability tool is in use, please run with -XX\:+EnableDynamicAgentLoading to hide this warning
WARNING\: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING\: Dynamic loading of agents will be disallowed by default in a future release

### Reproduction Steps

Start spark report (async I think?) on java 21

### Expected Behaviour

Shouldn't print this warning.

### Platform Information

* Minecraft Version: 1.20.6
* Platform Type: server
* Platform Brand: Paper 1.20.6

### Spark Version

v1.10.32

**Comment by lucko** [comment]
https://github.com/lucko/spark/commit/45ce159cda4a444fda437deae99452e8ed71493e
