### ISSUE TITLE
[Feature] Add additional SELF time spent by method call entry

### ISSUE THREAD

**Issue by i0xHeX** [lucko/spark#41]
Sometimes I see like method A tooks 1600ms, and childs take 200mc, 180mc, 130mc etc... < 500ms for example. And it's a bit difficult to count even approximate time, spent by method A itself. I think It would be great feature if we can see both ALL and SELF time spent (near each other in the graph).

In way like that:
https://i.imgur.com/aQmRz9t.png

**Comment by lucko** [comment]
Thanks for the suggestion - however, I don't think this is something I want to add for the time being. I'm trying hard to not clutter the interface up too much! And this is the sort of thing which is kinda implied anyway - and also not something that's common with other profilers.
