### ISSUE TITLE
[1.21] After installing the latest version of Mod the game crash

### ISSUE THREAD

**Issue by Periam** [lucko/spark#414]
### Description

Downloading and installing Spark Mod on MC 1.21, made the game crash on the verification stage of loading.
Minecraft 1.21
Forge 51.0.8
spark-1.10.73-forge

### Reproduction Steps

Install the mod on a MC 1.21 instance

### Expected Behaviour

To load the mod normally

### Platform Information

* Minecraft Version:  1.21
* Platform Type:  Client
* Platform Brand: Forge
* Platform Version: Forge 51.0.8

### Spark Version

 v 1.10.73-forge

### Logs and Configs

[crash-2024-06-17_13.04.52-fml.txt](https://github.com/user-attachments/files/15873904/crash-2024-06-17_13.04.52-fml.txt)

**Comment by P4YN-Ki** [comment]
Also getting the exact same issue. 
[crash-2024-06-20_02.21.08-fml.txt](https://github.com/user-attachments/files/15907220/crash-2024-06-20_02.21.08-fml.txt)

This is with spark as the only mod loaded.
