### ISSUE TITLE
Starting sampler from in-game can leak memory

### ISSUE THREAD

**Issue by aromaa** [lucko/spark#417]
### Description

There are few lambdas in the `SamplerModule` that will hold the reference of the command sender until the sampler is turned off. For example [this](https://github.com/lucko/spark/blob/dface5907890d3f832c79d9152d6a379ef22f429/spark-common/src/main/java/me/lucko/spark/common/command/modules/SamplerModule.java#L280) and [this](https://github.com/lucko/spark/blob/dface5907890d3f832c79d9152d6a379ef22f429/spark-common/src/main/java/me/lucko/spark/common/command/modules/SamplerModule.java#L293). This can be a problem if the command sender logs off and leaves the sampler on which causes the corresponding player object and the world they were in to be leaked.
![image](https://github.com/lucko/spark/assets/3258677/d0975ec5-d963-432c-98ca-7c755e0be227)

### Reproduction Steps

Start the sampler in-game and log off, the player object is leaked.

### Expected Behaviour

The player object is not leaked.

### Platform Information

* Minecraft Version: 1.20.6
* Platform Type: server
* Platform Brand: Sponge
* Platform Version: 1.20.6-11.0.1-RC1661

### Spark Version

v1.10.73

**Comment by lucko** [comment]
thanks :) should be fixed by the above commit
