### ISSUE TITLE
Unable to initialise the async-profiler engine: Event wall is not supported (With Java 21 OpenJ9)

### ISSUE THREAD

**Issue by NoltoxGit** [lucko/spark#420]
### Description

Hello,
When using an OpenJ9 version of Java (in my case, Java21 OpenJ9), I get a big error in my spark console.

### Reproduction Steps

1. Select a OpenJ9 java version.

### Expected Behaviour

No errros.

### Platform Information

* Minecraft Version: Minecraft 1.20.4
* Platform Type: Server
* Platform Brand: Purpur
* Platform Version:  git-Purpur-2176 (MC: 1.20.4)*

### Spark Version

v1.10.74

### Logs and Configs

https://mclo.gs/puxZ3Y2#L856

**Comment by SirYwell** [comment]
`async-profiler` only supports HotSpot VM. You can change the background profiler engine in the config if you actually want to use OpenJ9. Maybe the message could be improved for this specific scenario.

**Comment by lucko** [comment]
Resolved in 8379f2b07bc38c24733c4f1d537ea7c2ee03d91b
