### ISSUE TITLE
Flag --ignore-sleeping does not work?

### ISSUE THREAD

**Issue by i0xHeX** [lucko/spark#44]
I just tried to test new flags, and as I understood, `--ignore-sleeping` should ignore time, when server sleeps for tick and this means if tick took 25 ms, sampler should not record this, if threshold is 50ms.

My commands:
`/spark profiler --start --ignore-sleeping --only-ticks-over 50`
`/spark profiler --stop --order-by-time`

**Expected behaviour:**
Empty logs.

**Actual output:**
https://spark.lucko.me/#yKgkSTTzBC
Command `/spark tps`  shows that the maximum tick duration during a minute was 23.3ms, but logs show some data recorded.

**Comment by lucko** [comment]
Should be improved by bdc2641e0997775f87fd413d9cb12716f0abd2f5

**Comment by i0xHeX** [comment]
@lucko 
Data still recorded:

1.
`/spark profiler --ignore-sleeping --only-ticks-over 40`
`/spark profiler --stop`
https://spark.lucko.me/#s13PlCV0f3

2. 
`/spark profiler --ignore-sleeping --ignore-native --only-ticks-over 40`
`/spark profiler --stop`
https://spark.lucko.me/#HVC2jVFZwv

But `/tps` command (by spark) shows no more than ~29 ms tick duration (max) after recording completed.

**Comment by i0xHeX** [comment]
The same problem with `/spark tickmonitor --without-gc --threshold-tick 40`, it shows every tick, even if duration without sleeping < 50ms

![image](https://user-images.githubusercontent.com/33582973/80238675-7d4a5b80-8667-11ea-8022-5b994b15d30c.png)

**Comment by lucko** [comment]
Unfortunately, due to the way spark monitors ticks for this functionality, it is not possible to set a tick filter below 50ms (because the server sleeps to ensure all ticks are at least 50ms!)

**Comment by i0xHeX** [comment]
> Unfortunately, due to the way spark monitors ticks for this functionality, it is not possible to set a tick filter below 50ms (because the server sleeps to ensure all ticks are at least 50ms!)

But you can measure exact tick durations excluding sleep by events in recent versions, the same way you display them in /spark health (Tick Durations)
