### ISSUE TITLE
Permissions not functioning in Paper-1.21.1 bundled edition of spark

### ISSUE THREAD

**Issue by IngeniousCoder** [lucko/spark#444]
### Description

Permissions documented at https://spark.lucko.me/docs/Command-Usage, such as 
```
spark.profiler
spark.healthreport
spark.ping
spark.tps
spark.tickmonitor
spark.gc
spark.gcmonitor
spark.heapsummary
spark.heapdump
spark.activity
```

do not work on Paper-1.21

Additionally, when dumping out permission tree with Luckperms (/lp tree), permissions are not reflected as well. [See here](https://luckperms.net/treeview/8M6I2YjGqq)

### Reproduction Steps

1. Install a clean version of Paper-1.21
2. Confirm bundled spark plugin exists.
3. Using /lp tree or /lp permission set, can confirm that spark permissions do not work.

### Expected Behaviour

The spark permission nodes should work.

### Platform Information

* Minecraft Version: 1.21.1
* Platform Type: server
* Platform Brand: Paper
* Platform Version: Paper version 1.21.1-35-master@be1078f (2024-08-18T22:41:36Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Spark Version

v1.10.84 (bundled with 1.21.1-35)

**Comment by Doc94** [comment]
The only permission working is the 'spark' for me.

**Comment by IngeniousCoder** [comment]
Can confirm. 

But the subnodes should work per the documentation. That's the issue.
