### ISSUE TITLE
Privacy issues

### ISSUE THREAD

**Issue by SrLeojaco** [lucko/spark#47]
As i was reading the spark-web project is just a reader-data from another storage provider. Would be possible to set own-storage provider?

**Comment by SrLeojaco** [comment]
Already realised how to do. I would suggest making a quick-wiki guide in order to do so

**Comment by astei** [comment]
I'm working on a [redo of the web UI](https://github.com/astei/spark-ignition) and may be interested in including local file-reading functionality. (The UI always parsed the data itself - the profiler data was just stored on an external service.)

**Comment by lucko** [comment]
Yep, I can make the link configurable too.
