### ISSUE TITLE
error: Thread filter does not match thread? 

### ISSUE THREAD

**Issue by k1r0s** [lucko/spark#48]
First of all thanks for creating this wonderful plugin.

After running a sampler I find this message: "Thread filter does not match thread"

here is the result -> https://spark.lucko.me/#51uA6oI4sm

**Comment by lucko** [comment]
What command did you use to activate the sampler?

**Comment by k1r0s** [comment]
I did:

`/spark sampler --only-ticks-over <x> `

however im unable to reproduce it again so, ye, nvm :)
