### ISSUE TITLE
web page unresponsive and glitchy

### ISSUE THREAD

**Issue by PhanaticD** [lucko/spark#54]
often have to wait a few seconds for things to happen, I am using chrome, like I will click on a expand button a few times, then nothing will happen then it will suddenly expand and contract a ton of times very quickly

**Comment by PhanaticD** [comment]
https://gyazo.com/7ce256a65375aec734cd711941b012c8

**Comment by astei** [comment]
[spark-ignition](https://github.com/astei/spark-ignition) should fix this issue, when I get it finished and feature-equivalent to the current profiler UI.

**Comment by lucko** [comment]
Should be resolved now, the React rewrite astei worked on has now been merged into the main project and deployed :))
