### ISSUE TITLE
Add some server information to profiler reports

### ISSUE THREAD

**Issue by Phoenix616** [lucko/spark#56]
It would be useful for easier debugging and stuff if profiler reports would include some information about the server software and version used and that to be visible on the web page too.

**Comment by md678685** [comment]
@lucko Mind if I have a go at implementing this?

**Comment by md678685** [comment]
Spark now includes the platform type (client/server/proxy), platform name (Bukkit/Paper/Bungee etc), Minecraft version (where applicable) and platform version in the payload. lucko/spark-web#4 will add this data to the web interface once it's merged.
