### ISSUE TITLE
Request - Ability to run tps and commands in console

### ISSUE THREAD

**Issue by tjsd** [lucko/spark#66]
Hello!
I like to check the servers performance in console, but you require a player to run the commands.
Could you add support to run the basic commands in console?

Also, a command to list all entities and a command to kill specific enteties would be amazing!

**Comment by Titaniumtown** [comment]
PLEASE add this!!!!!

**Comment by lucko** [comment]
Which platform are you using spark on? Bukkit, Forge, Fabric??

**Comment by tjsd** [comment]
Fabric on 1.16.1

**Comment by lucko** [comment]
Should be all sorted now in the latest release, sorry it took a while!
