### ISSUE TITLE
Sampler won't upload 

### ISSUE THREAD

**Issue by heyheyhey123243** [lucko/spark#67]
Was unsure if anyone could help on discord so just reposting my issue here. 

I tried running the profiler on my singleplayer world until the TPS started dropping. I tried ending the profiler after the lag started but it would not upload. 

https://pastebin.com/hMz8YjRi - Here is the error

**Comment by lucko** [comment]
Perhaps a firewall / antivirus blocking the upload? No idea beyond that, sorry.
