### ISSUE TITLE
Is there a way to export the data collected from Spark?

### ISSUE THREAD

**Issue by RecipeForTears** [lucko/spark#74]
Hi, I am wondering if it is possible to export the data in Spark to Excel as a csv or xlsx, or any other similar format. Would appreciate the help, thanks!

**Comment by lucko** [comment]
Hi, unfortunately there is no way to export to csv.

Spark uses protobufs (protocol buffers) to encode data and send it to the viewer. In theory, you could decode that if you really wanted to analyse the raw data.

I'm not sure quite why you'd want to do that though.. :)
