### ISSUE TITLE
Version for 1.16.1 Download

### ISSUE THREAD

**Issue by Kijan** [lucko/spark#79]
Hi

I wanted to use your mod for 1.16.1 but there are only the last 5 builds on your site. are the older builds somewhere to download? i would need to download #148 i assume, because of a message on reddit. but the lowest number available is #151

**Comment by Kijan** [comment]
:(

**Comment by lucko** [comment]
Sorry, the old builds don't get kept for very long. I don't have any jars to hand for 1.16.1, your best bet would be to build the project from a 1.16.1 commit.
