### ISSUE TITLE
Fabric: CommandSender should not be checking just DedicatedServer

### ISSUE THREAD

**Issue by i509VCB** [lucko/spark#80]
I noticed that [FabricCommandSender here](https://github.com/lucko/spark/blob/master/spark-fabric/src/main/java/me/lucko/spark/fabric/FabricCommandSender.java#L48) falls back to check only the dedicated server for the command executor.

This should probably check if the delegate is a `MinecraftServer` and `RconCommandOutput`. `MinecraftServer` because of the integrated server and `RconCommandOutput` for any rcon connections invoking the profiler.

**Comment by lucko** [comment]
7497f91084b5a0b220e3c32612803fc0bfd2fc6e thanks!
