### ISSUE TITLE
Running from rcon console? (Fabric)

### ISSUE THREAD

**Issue by vpzomtrrfrt** [lucko/spark#82]
Probably related to #30 

I'm trying to run this on a Fabric server, but the command fails with "A player is required to run this command here" when I attempt to execute it in RCON

**Comment by lucko** [comment]
I'm not sure why this is - there isn't a string like that anywhere in spark, so I assume the limitation is coming from the server itself.

As far as I can tell, everything is being registered correctly on the spark side.

**Comment by vpzomtrrfrt** [comment]
See #40, a very similar change (but adapted to yarn mappings) resolved it for me

**Comment by lucko** [comment]
Ah awesome, thanks
