### ISSUE TITLE
Sampling results not working from today

### ISSUE THREAD

**Issue by kaziu687** [lucko/spark#83]
Every sampler result url stopped working today. When you visit url there is "Unable to load the data. Perhaps it expired? Are you using a recent version?" error. Example urls:
* (2020-12-09 14:14:37) https://spark.lucko.me/#zpugVaYOYp
* (2020-12-15 22:07:55) https://spark.lucko.me/#Tq807Slnz9

**Comment by lucko** [comment]
Well.. are you using a recent version?

The viewer dropped support for the old profile format that was phased out a few months ago. If you haven't updated since then, it won't work until you update your plugin.
