### ISSUE TITLE
Support heap dump summary on OpenJ9 or throw a more helpful error

### ISSUE THREAD

**Issue by prajaybasu** [lucko/spark#85]
[~~HeapDump.java~~](https://github.com/lucko/spark/blob/master/spark-common/src/main/java/me/lucko/spark/common/heapdump/HeapDump.java) ~~assumes that it is running on a HotSpot based JVM~~:

When the ~~heapdump~~ heapsummary command is executed on an OpenJ9 based JVM, an exception is thrown:  
``` 
System Info: Java 15 (Eclipse OpenJ9 VM master-d4cc28f41) Host: Windows 10 10.0 (amd64)
...  
[WARN]: java.lang.RuntimeException: Unable to get heap dump
[WARN]:        at me.lucko.spark.common.heapdump.HeapDumpSummary.createNew(HeapDumpSummary.java:98)
[WARN]:        at me.lucko.spark.common.command.modules.HeapAnalysisModule.lambda$null$0(HeapAnalysisModule.java:73)
[WARN]:        at me.lucko.spark.common.command.modules.HeapAnalysisModule$$Lambda$5802/0x00000000f9c73198.run(Unknown Source)
``` 

I don't know how much effort it will be to add OpenJ9 support, but the plugin should detect if it is running on OpenJ9 and appropriately disable the command until heap dump *summary* support for the .PHD format can be added. 

~~Relevant: https://github.com/eclipse/openj9/issues/6593~~

**Comment by lucko** [comment]
> HeapDump.java assumes that it is running on a HotSpot based JVM:

No.. it doesn't. It explicitly has a check for OpenJ9 😛 

https://github.com/lucko/spark/blob/737c09973ab6a45cbaa5bdbad24632b0fb23ce07/spark-common/src/main/java/me/lucko/spark/common/heapdump/HeapDump.java#L51-L54

Now.. perhaps that API has changed since, but that's an entirely different issue.

**Comment by prajaybasu** [comment]
> No.. it doesn't. It explicitly has a check for OpenJ9 😛
Ah, I missed that 🤦

> Now.. perhaps that API has changed since, but that's an entirely different issue.

Actually, the heap dump function works just fine. Heap Summary does not, however.

**Comment by lucko** [comment]
Ah, right yeah.

Unfortunately OpenJ9 doesn't support the heap summary functionality (afaik) so you are limited to full help dumps only. Nothing I can do about this in spark I'm afraid.
