### ISSUE TITLE
Add back search function and right click to profiler website

### ISSUE THREAD

**Issue by kentos01** [lucko/spark#86]
Latest spark update honestly feels like a massive step backwards with the removal of the search bar, one of the most useful tools and removal of right clicking to expand recursively/collapse, another useful tool. It would be great if these were added back. Thanks!

**Comment by lucko** [comment]
There is already an open issue for search: https://github.com/lucko/spark-viewer/issues/15

Feel free to make another on that repo for right click expand/collapse.
