### ISSUE TITLE
Compatibility with mcMMO?

### ISSUE THREAD

**Issue by andrewkm** [lucko/spark#87]
Getting this on startup:
`[21:59:47] [Server thread/WARN]: [mcMMO] Loaded class net.kyori.examination.Examinable from spark v1.4.3 which is not a depend, softdepend or loadbefore of this plugin.`

mcMMO developer stating it's an issue on spark's side (@nossr50)
https://github.com/mcMMO-Dev/mcMMO/issues/4364

**Comment by andrewkm** [comment]
Fixed via: https://github.com/mcMMO-Dev/mcMMO/commit/a39c7420b94d9c5a97f50a19025c5754ef819343

**Comment by nossr50** [comment]
My bad, I wasn't properly relocating that library.

**Comment by lucko** [comment]
Ah, seems like I'm not relocating it either, will fix, thanks!
