### ISSUE TITLE
[Feature Request] Don't profile when no players are on

### ISSUE THREAD

**Issue by Titaniumtown** [lucko/spark#89]
Can an argument to the `spark profiler` command be added something along the lines of `--ignore-no-players` that doesn't run the profiler when no players are on the server?

**Comment by Titaniumtown** [comment]
I would really like this feature, I hope it gets implemented soon!

**Comment by lucko** [comment]
You shouldn't be running the profiler for long periods of time and/or unattended anyway, so I don't see a good reason to add this.

spark is most useful when used for short-ish periods of time (1-2 mins) only when you are experiencing a performance issue. Therefore, there is no reason why it should ever be started / running when there are no players on the server.
