### ISSUE TITLE
CPU Utilization Doesn't Work

### ISSUE THREAD

**Issue by AabegR** [lucko/spark#90]
Hello there, the CPU Utilization placeholder doesn't work on my server machine, but it does on my regular pc. Odd.

I even copied the same files from the non-working server onto my pc, and it works right away, and vice versa - working server to non-working.

It's stuck at 0 percent CPU use, but that's kind of not possible...
Everything else works 10/10. I really appreciate this plugin probably something is wrong on my end.
Hewp

**Comment by lucko** [comment]
For whatever reason, the Java VM and corresponding accessor methods are not able to retrieve the CPU usage info.

We use the OperatingSystem management factory bean:

https://github.com/lucko/spark/blob/8afbad26d965204b48df9da534fb931c16558887/spark-common/src/main/java/me/lucko/spark/common/monitor/cpu/CpuMonitor.java#L41-L42

There's nothing spark can do to fix this unfortunately, and I don't really have any ideas of things to try either, sorry!
