### ISSUE TITLE
Let us run a command when the URL is generated so we can send it where we want.

### ISSUE THREAD

**Issue by TomLewis** [lucko/spark#93]
When you set a profiler to go, it'll output to the console, Now I have a busy console lots of people talking and doing things, this is not a good way to get feedback if I'm not in-game!

Really simple request, let us run a command when the url is generated. 
Then we can send it to a private discord channel using Discord SRV, we can send it into our admin chat, we can send it to a script that pings it to pushbullet once its finished, it gives us the option to output it to a source where we want.

**Comment by lucko** [comment]
I think this is a bit too niche to be included in spark itself.

Perhaps you could ask the DiscordSRV developers if they would consider adding such a feature to DiscordSRV -- either to execute commands using a custom command sender then relay the response back, or some sort of regex match to catch console messages...?

**Comment by TomLewis** [comment]
It just needs to fire an event when it's done so we can see that it's done without being in-game, not niche, just quality of life.
