### ISSUE TITLE
1.16.4 Forge server doesn't load spark

### ISSUE THREAD

**Issue by terrytzh** [lucko/spark#94]
Hi, I am trying to add spark to my 35.1.36 forge server, yet the server doesn't load spark as "spark-forge.jar is for an older version of Forge and cannot be loaded," a warning in the terminal during the booting process. Do I have to downgrade my forge in order to use spark?

**Comment by linx80** [comment]
Same issue on my server running 36.0.10.

**Comment by lucko** [comment]
It should just work™️ 

I can't reproduce this using the latest 1.16.4 Forge release.
