### ISSUE TITLE
CPU Utilization issue

### ISSUE THREAD

**Issue by kmecpp** [lucko/spark#98]
With Pterodactyl you can allocate a certain number of cpu cores to each server. For some reason this confuses the Spark CPU monitor which consistently thinks the system CPU load is out of the number of cores available to the docker the server is running in and not the real number of cores available to the system.

This leads to a very high reported utilization (usually consistently 100% but the server wasn't that active when I took the screenshots) but the actual server utilization is much lower

![image](https://user-images.githubusercontent.com/6520738/106825254-7cad0f80-6652-11eb-9841-a7a25dfb3f16.png)
Running on a 4 core 8 thread system so load average numbers should get up to 4 or 8.

![image](https://user-images.githubusercontent.com/6520738/106825751-84b97f00-6653-11eb-9d41-7fe7dbb062f2.png)

**Comment by lucko** [comment]
Spark gets this info from the [OperatingSystemMXBean](https://docs.oracle.com/javase/8/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html).

If the values are incorrect, then that's probably a JVM issue - not much I can do to fix, sorry!
