### ISSUE TITLE
Include version / target MC version in filename

### ISSUE THREAD

**Issue by NolanSyKinsley** [lucko/spark#99]
Title pretty much says it all. It's a good habit to append at least the mod version number to the end of the filename of the downloads on curseforge, if not the MC version followed by the mod version so people can tell at a glance if they are loading/copying the correct mod version when manipulating server files.

**Comment by lucko** [comment]
25f46b649363d99f51b1b5262b5f7c0ce0c3251b

The version will also now automatically increment after each change/commit (like LuckPerms)

Updated on the spark downloads page (https://spark.lucko.me/download) - subsequent releases to SpigotMC and CurseForge will also have the versions in the file name :)

Sorry it took me a while to get around to it!
